# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

before_build:
#  - cp travis-tool.sh pkg\travis-tool.sh
#  - cp travis-tool.sh.cmd pkg\travis-tool.sh.cmd
  - cd pkg
  - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"
  
build_script:
  - travis-tool.sh install_deps
  
test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: 'pkg\*.Rcheck\**\*.log'
    name: Logs

  - path: 'pkg\*.Rcheck\**\*.out'
    name: Logs

  - path: 'pkg\*.Rcheck\**\*.fail'
    name: Logs

  - path: 'pkg\*.Rcheck\**\*.Rout'
    name: Logs

  - path: 'pkg\*_*.tar.gz'
    name: source

  - path: 'pkg\*_*.zip'
    name: binary

version: 0.5.1-{build}

branches:
  only:
  - master

notifications:
  - provider: Email
    to: mclogit@elff.eu
    on_build_success: change
    on_build_failure: true

deploy:
  provider: GitHub
  auth_token:
    secure: dmzZ4ohXYLWbEtp4RW9xBSEFtIirUua57jeak2h6yu/g90RoxnVwLxwpkeVPKrdh
  artifact: source,binary 

  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
  
